### ISSUE TITLE
根据主键修改数据无效

### ISSUE THREAD

**Issue by zhouxin93** [SkyChenSky/Sikiro.DapperLambdaExtension.MsSql#2]
当不写where条件。直接update应该是根据主键来修改数据库。但是这种情况下数据库的所有数据都被修改了。

**Comment by SkyChenSky** [comment]
我这里测试了没问题，不知道是不是你的model.id没有修改到？才会导致修改了同一条数据

**Comment by SkyChenSky** [comment]
之前刚那个Update的问题的确是我没测试到的场景，我的疏忽，非常抱歉。也非常感谢你的积极反馈，很有价值

**Comment by zhouxin93** [comment]
修改到了。每次都会拿到新的id。你使用不同的条件查询出来不同的记录。然后再去修改它看看

**Comment by SkyChenSky** [comment]
方便发你那段代码看看不，我现在需求评审，不方便调试

**Comment by zhouxin93** [comment]
`var item = await shareLogRepository.GetItem(userid, model.postsid);`
`var list = item.ShareTo.SplitToList(',');
				if (model.shareto.Length > 0 && !list.Contains(model.shareto))
				{
					list.Add(model.shareto);
					item.ShareTo = string.Join(",", list);

					isFlag = await shareLogRepository.UpDateAsync(item);
				}`
`public async Task<bool> UpDateAsync(ShareLog model)
		{
			using (var conn = db.GetDbConn(dbKey.BBS))
			{
				var res = (await conn.CommandSet<ShareLog>().Where(a => a.Id == model.Id).UpdateAsync(model)) > 0;
				return res;
			}
		}`

**Comment by zhouxin93** [comment]
这传上来格式有点乱。就是正常的根据体检查询一条数据。修改数据然后更新到数据库

**Comment by zhouxin93** [comment]
这传上来格式有点乱。就是正常的根据条件查询一条数据。修改数据然后更新到数据库

**Comment by zhouxin93** [comment]
另外建议数据库操作增加异步的封装。NetCore 在Linux 异步性能更高点。

**Comment by SkyChenSky** [comment]
找到你刚刚说的缓存问题了，的确在TrimExpression里调用的时候MemberToValue，想把委托存到内存提高效率，但是却引起了解析出的value一致的问题。我暂时把缓存屏蔽了修复一下，迟点再优化这块。谢谢反馈
