### ISSUE TITLE
只有Or条件时候生成sql错误。

### ISSUE THREAD

**Issue by zhouxin93** [SkyChenSky/Sikiro.DapperLambdaExtension.MsSql#3]
True || $expression.Id == .Constant<CaiTu.Api.Repository.UserRepository+<>c__DisplayClass5_0>(CaiTu.Api.Repository.UserRepository+<>c__DisplayClass5_0).id
|| $expression.Id == .Constant<CaiTu.Api.Repository.UserRepository+<>c__DisplayClass5_0>(CaiTu.Api.Repository.UserRepository+<>c__DisplayClass5_0).id
 
当只有Or条件时候会生成这样的where条件。

WHERE ((@ OR (Id = @Id)) OR (Id = @Id)) 

我这边适当修改了一些。WhereExpression.SetParam(string fileName, object value) 内部应该将单个True转换为1=1就OK了

**Comment by SkyChenSky** [comment]
有使用init不？

**Comment by zhouxin93** [comment]
var where = ExpressionBuilder.Init<User>()

**Comment by zhouxin93** [comment]
`var where = ExpressionBuilder.Init<User>()`

**Comment by SkyChenSky** [comment]
我迟点看看，谢谢哈

**Comment by zhouxin93** [comment]
`Where(g => g.CreateTime >= checkDate)`   使用这样的where条件也会报错

**Comment by SkyChenSky** [comment]
我好奇的问一下，你是第一个问题是不是绕过了
```c#
var where = ExpressionBuilder.Init<User>()
```
来使用
```c#
var where = ExpressionBuilder.Or<User>()
```

**Comment by zhouxin93** [comment]
没有哦。先Init。再Where的。错误是因为True条件
在`SetParam(string fileName, object value)` 里True条件只拼上了一个 @

**Comment by SkyChenSky** [comment]
好，我现在看看

**Comment by zhouxin93** [comment]
OK。`g.CreateTime >= checkDate` 这个是因为CreateTime 使用了可空类型的。就会出错。这边已改成不可空

**Comment by SkyChenSky** [comment]
第一个问题，我在TrimExpression里改了，原本AndAlso已经把默认的True去了，但是OrElse缺漏了。你看看这样改会不会更加好一点。

**Comment by SkyChenSky** [comment]
已修改，谢谢提出
